In [1]:
s1=[3,6]
s2=[8,10]
s3=[]
i=0
j=0
for i in s1:
    for j in s2:# in this loop overwrites and 3 becomes 4 similarly with one addition 6 becomes 7
        s3.append((j,i))
        i +=1
        j +=1
print(s3)

[(8, 3), (10, 4), (8, 6), (10, 7)]


In [3]:
import numpy as np #class of numpy
import pandas as pd

In [4]:
#numerical #python numpy is basically array # n dimensional array
#book=>
# image processing include a lot numpy

In [5]:
# it is a manipulation of sequences of homogenous data items

In [6]:
#physical quantities there are two type scalar and vector 
# scalar only requires number but not direction and units # mass
# vector requires both magnitude and direction Weight
# example students sitting in class if there is a student sitting with id he could be sitting anywhere . but if we want to give postion of that student we use a reference where he is sitting with other student who is wearing glasses 
# vector is in space kisi bhi position sai reference dena parta hai

In [7]:
# when we comapre two numpy it will return true and false
# there is slicing in numpy
#numpy is very fast in computing squares and vectorized operation
#magic_function =>time it

In [8]:
array_to_square=np.arange(0,10000)


In [9]:
%timeit array_to_square **2

8.3 µs ± 63.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
#10000 time less is consume in numpy

In [11]:
#datascience and machine learning is dependent on numpy
#cloud pr processing bohat fast hai google cloud platform provides fast processing
#https://colab.research.google.com/notebooks/welcome.ipynb#recent=true
a1=np.array([1,2,3,4,5],dtype=float)# list is converted into array # data type could be converted into float but default is int

In [12]:
a1

array([1, 2, 3, 4, 5])

In [13]:
a1*2 # vector operations 

array([ 2,  4,  6,  8, 10])

In [14]:
a1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [15]:
a1+1

array([2, 3, 4, 5, 6])

In [16]:
a1+a1

array([ 2,  4,  6,  8, 10])

In [17]:
a2=np.array([3,6,7])
print(a2)

[3 6 7]


In [21]:
a2=np.arange(1,10)# start # end # step in array
print(a2)

[1 2 3 4 5 6 7 8 9]


In [23]:
a2=np.arange(2,10,2)#start # end #step
print(a2)

[2 4 6 8]


In [24]:
#one dimension array is called vector

In [25]:
#if number is passed it is a scalar quantity and it's dimension is 0

In [26]:
s1=np.array(1)
s1.ndim

0

In [28]:
dim_2=np.array([[1,2,3,4],[5,6,7,8]])
print(dim_2)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
dim3=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # bracket ko dekh kar dimension ka andaza laagaya jasakta hai kitna dimension hai
print(dim3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [32]:
dim3.ndim

3

In [33]:
dim3.size

9

In [35]:
type(dim3)

numpy.ndarray

In [36]:
np.size(dim3)# the quantity of elements

9

In [38]:
np.ndim(dim3)

3

In [40]:
#agar ek bhi float ajae to sab float hojae ga   #learning pandas
s3=np.array([0]*10)
print(s3)

[0 0 0 0 0 0 0 0 0 0]


In [41]:
#python ki range sai list bnayi phir convert karley array kie

In [42]:
np.array(range(10))#array ki waja sai list bani hai

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.ones(12).reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [49]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [50]:
np.zeros(12).reshape(2,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [56]:
sq=np.array([1,2,3,4,5,6]).reshape(3,2)
print(sq)

[[1 2]
 [3 4]
 [5 6]]


In [61]:
np.linspace(0,20,11)#it will equally divide into 11 # har ek kai darmian 11 hoga space 

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [64]:
arr2=np.linspace(0,50,20)

In [67]:
np.size(arr2) # sab sai pehly jo data recieve horaha hai uska size kia hai

20

In [71]:
d2=np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(d2)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [72]:
d2[1,4]# row phir column

15

In [73]:
#randomint generate numbers

In [76]:
w=np.random.randint(5,10)
print(w)

9


In [77]:
w=np.random.random_integers(1,10)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """Entry point for launching an IPython kernel.


In [84]:
import random
list1=[]
for x in range(10):
        list1.append(random.randint(1,101))
        
print(list1)

[50, 58, 17, 34, 40, 56, 1, 66, 18, 34]


In [88]:
w=np.random.randn(50).reshape(5,10)
w

array([[ 1.8948167 ,  0.78433886, -0.97043073,  0.43757524, -1.15470437,
         0.99657732,  0.66968239,  1.19700002,  1.57878138, -0.34574133],
       [-0.56459411, -0.54804108, -1.04725902, -0.72264575,  0.37905067,
         1.87536015, -0.60594551,  0.64543056,  1.80480724, -0.3052463 ],
       [-0.39440701, -1.34674968, -0.67780137,  1.72124952, -0.14714128,
         0.60049061,  0.42960116, -0.84542572, -0.5471648 ,  1.81151575],
       [-1.25087544,  0.74522937,  1.27344959, -0.8269885 , -2.26025147,
         2.2918269 ,  0.12488591, -0.05592983,  0.37685923,  1.16207433],
       [-0.23475912,  0.07244547, -0.26531727,  0.51047328,  0.06648918,
        -0.7360621 ,  1.2904269 , -1.17768841,  0.40919619, -1.82100912]])

In [89]:
w[1:3,4:5]

array([[ 0.37905067],
       [-0.14714128]])

In [92]:
n1=([[1,2,3],[4,5,6]])
np.array(n1)

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
#jitna dimension array ko slice karey gai utna hi dimension ayega

In [95]:
print(n1)

[[1, 2, 3], [4, 5, 6]]


In [97]:


#indexing returns value
#but n1 slicing returns an array or matric

In [99]:
#slicing in integers