In [1]:
#python for data analysis
#dictionary comprehension ,decorators


In [6]:
#many numpy arrays are known tensor
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [3]:
import numpy as np

In [5]:
data=np.array(my_list)
#list sai array create kardia numpy ka array
#array list ka alternate hai
type(data)
print(data)

[1 2 3]


In [7]:
#dono hi array hai ek python ka list hai
data.dtype #array kai andar ki type dtype sai check karte hai
#numpy ek hi data type ko support karta hai ek waqt mei

dtype('int32')

In [8]:
x=[1,2,3,'true',True]
data1=np.array(x)

In [9]:
print(data1)

['1' '2' '3' 'true' 'True']


In [11]:
data1.dtype

dtype('<U11')

In [18]:
#image ek colour picture 3 dimension hoti hai
#numpy ka ek faida vector operations bohat asani sai hojatey hai
list_2=[1,2,3],[2,3,4]
data2=np.array(list_2)
print(data2)
print(data2.ndim)
print(data2.shape)

[[1 2 3]
 [2 3 4]]
2
(2, 3)


In [16]:
#dimension kitney axis mujood hai
#nshape hamei ek axis mei kitni rows or kitney columns hai
#list vector operations ko support nahi karti
#numpy python ki list sai bohat fast hai
new_list=[1,2,3]
old_list=[4,5,6]
new_list=old_list+new_list
print(new_list)

[4, 5, 6, 1, 2, 3]


In [22]:
new_list1=np.array([1,2,3])
old_list1=np.array(old_list)
print(new_list1-old_list)

[-3 -3 -3]


In [23]:
#in list there is no subtraction but in np.array there is subtraction
# every airthmetic operations could be perform in numpy 

In [24]:
new_list1=np.array([1,2,3])
old_list1=np.array(old_list)
print(new_list1*old_list)

[ 4 10 18]


In [25]:
new_list1=np.array([1,2,3])
old_list1=np.array(old_list)
print(new_list1/old_list)

[0.25 0.4  0.5 ]


In [26]:
data_3=np.arange(10)#series create kardeta hai ranage
x=list(range(10)) #range kai function sai list create nahi hoti
print(x,data_3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0 1 2 3 4 5 6 7 8 9]


In [29]:
#single value wala scalar kehlata hai (2)
#magar ek dimension array ko vector kehtey hai([1,2,3])
scalar=np.array(5)
print(scalar)
print(type(scalar))
x=5
print(type(x))
print(scalar.ndim)
print(scalar.shape)#uski koi axis hi nahi

5
<class 'numpy.ndarray'>
<class 'int'>
0
()


In [36]:
scalar=np.array([[5,4],[6,3],[7,2]])
print(scalar)
print(type(scalar))
x=5
print(type(x))
print(scalar.ndim)
print(scalar.shape)#uska ek axis hai ab

[[5 4]
 [6 3]
 [7 2]]
<class 'numpy.ndarray'>
<class 'int'>
2
(3, 2)


In [41]:
scalar=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(scalar)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [44]:
#random numbers in 20 % in python
#test mei ayega module
#mei ek kaam karaha hun ek hi code mei bohat messy hogaya code 
#ab ek alag file bnali jisko module kehtey hai alag sai to alag file kia function ko apney code mei call karney ko module kehtey hai
import numpy as np # this is calling of
#from math import add,math

In [51]:
n = np.array([[1, 2, 3,4], [4, 5, 6,7],[1,2,3,4]])
print(n)
print(n.shape)

[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]]
(3, 4)


In [49]:
#agar numpy kai random numbers ka array generate karna hoga

In [58]:
data= np.random.randn(2,4)# ek random number genereate karlie jiske 2 rows and 3 columns hai
print(data.astype(np.int64))

[[ 0  0  0 -1]
 [ 1  0  0  0]]


In [60]:
data.dtype=int
print(data)

[[ -616662629 -1075272932 -2129816883  1072234166  -578365866  1070939885
   2029234888 -1074132058]
 [-1413290744  1073233270  -884422180  1072326792   838494734  1069645557
  -1436115391 -1076252838]]


In [61]:
data= np.random.randn(2,3)# ek random number genereate karlie jiske 2 rows and 3 columns hai
print(data.astype(np))

[[-2.2560888292985637 -0.7834626172330023 -0.5155770861344361]
 [0.1129074468235555 0.9196814454302953 -1.7539110205880637]]


In [64]:
data= np.random.randn(2,4).astype(int)# ek random number genereate karlie jiske 2 rows and 3 columns hai
#print(data.astype(np.int64))
print(data)

[[ 0  0 -1  0]
 [ 0 -1  0 -1]]


In [66]:
data_ki_type=np.array([1.5,5,9,63],dtype=int)
print(data_ki_type)

[ 1  5  9 63]


In [71]:
data_ki_type.dtype=float

In [72]:
print(data_ki_type)

[1.06099790e-313 1.33685735e-312]


In [74]:
data= np.random.randn(2,4).astype(float)# ek random number genereate karlie jiske 2 rows and 3 columns hai
#print(data.astype(np.int64))
print(data)

[[-0.76390057  0.0273991  -0.72587485  2.2014813 ]
 [-0.40972888 -0.11252313 -1.17516928 -0.7318598 ]]


In [91]:
data=np.array([[2,3],[4,5],[3,4],[5,6]])
print(data)
print(data.shape)
print(data[:][:])

[[2 3]
 [4 5]
 [3 4]
 [5 6]]
(4, 2)
[[2 3]
 [4 5]
 [3 4]
 [5 6]]


In [82]:
#vscode and pycharm is better

In [92]:
data_5=np.arange(20).reshape((4,5))#kiu reshape nahi bnraha izka vector nahi bn paraha
print(data_5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [93]:
data_5=np.arange(15).reshape((3,5))#kiu reshape nahi bnraha izka vector nahi bn paraha
print(data_5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [94]:
data_5=np.arange(11).reshape((3,5))#kiu reshape nahi bnraha izka vector nahi bn paraha
print(data_5)

ValueError: cannot reshape array of size 11 into shape (3,5)

In [100]:
data_5=np.arange(1,76).reshape((25,3))#kiu reshape nahi bnraha izka vector nahi bn paraha #75 is 76-1=75
print(data_5)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]
 [55 56 57]
 [58 59 60]
 [61 62 63]
 [64 65 66]
 [67 68 69]
 [70 71 72]
 [73 74 75]]


NameError: name 'data5' is not defined

In [103]:
data_5.ndim

2

In [104]:
data_5.reshape((3,25))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75]])

In [107]:
data6=np.zeros(10).reshape(2,5)

In [109]:
data7=np.zeros((5,5))
print(data7)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [110]:
data7=np.zeros((5,5))
print(data7)
#2dimension shows x and y axis #3dimension shows x,y and z axis

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [114]:
data_6=np.ones((5,5))*5 # by default data type of float in numpy array
print(data_6)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [117]:
data3=np.eye(5,5)
print(data3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [122]:
data3=np.empty((5,5,6))
print(data3)

[[[1.01495556e-312 1.01546555e-312 1.01495555e-312 1.01496792e-312
   1.01540824e-312 1.01496720e-312]
  [1.01540825e-312 1.01496720e-312 1.01540826e-312 1.01496720e-312
   1.01540800e-312 1.01496720e-312]
  [1.01540799e-312 1.01496720e-312 1.01540800e-312 1.01496720e-312
   1.01540799e-312 1.01496720e-312]
  [1.01540800e-312 1.01480489e-312 1.01496720e-312 1.01546554e-312
   1.01495555e-312 1.01540800e-312]
  [1.01496720e-312 1.01546553e-312 1.01495555e-312 1.01540799e-312
   1.01496720e-312 1.01546555e-312]]

 [[1.01495555e-312 1.01495556e-312 1.01542306e-312 1.01495555e-312
   1.01496792e-312 1.01495556e-312]
  [1.01540799e-312 1.01495555e-312 1.01540799e-312 1.01496720e-312
   1.01540805e-312 1.01495555e-312]
  [1.01540804e-312 1.01496720e-312 1.01540805e-312 1.01495555e-312
   1.01540806e-312 1.01496720e-312]
  [1.01540805e-312 1.01495555e-312 1.01546555e-312 1.01495556e-312
   1.01496720e-312 1.01495556e-312]
  [1.01546450e-312 1.01495555e-312 1.01546450e-312 1.01496720e-312
   1

In [123]:
n1=np.array([[[3,3],[3,4]]])
print(n1.ndim)

3


In [124]:
#np.empty is not necessary every time it produce zeros but sometime it could give garbage in empty
data3=np.empty((1,1,1)) #it is 3 dimension
print(data3)

[[[8.6595007e-316]]]


In [132]:
#indexing in array
index_array=np.arange(25).reshape((5,5))
index_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
#kisi bhi element ko acess karna hai to uska index use karna pareyga
#index_array[row,column] # kisbhi index ko acess karna hoga ko to uskey rows or column pass karney parey gai

In [137]:
print(index_array[2,2])

12


In [138]:
#indexing in array
index_array=np.arange(36).reshape((9,4))
index_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [140]:
print(index_array[4,1]) # from zero rows to four rows and zero columns to four columns 

17


In [144]:
print(index_array[-8,-3]) # from neechy sai upar rows (-8) and right sai left columns (-3) 

5


In [145]:
#list slicing
list_1=[1,2,3,4,5]
print(list_1[2:4])

[3, 4]


In [146]:
#for two dimensions sai slicing
index_array=np.arange(36).reshape((9,4))
index_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [147]:
index_array[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [149]:
index_array[1:8,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22],
       [24, 25, 26],
       [28, 29, 30]])

In [150]:
# numpy ka array kese generate hojata hai
# numpy ki type ko kese type change karni hai
#zeros , ones and how to create arrays of five
#if any one is float in array there would every element in array in float
# 3 dimensional arrays
#there are two ways to create arrays and using np.array and np.arange
data_3dim=np.array([[[1,2,3],[2,3,4],[4,5,6]]])

In [151]:
print(data_3dim.ndim)

3


In [152]:
#element jitna bhi ho uskey brackets sai hi pata chaley ga kitna dimension hai

In [154]:
print(data_3dim.shape)

(1, 3, 3)


In [156]:
#dimension axis ko refer karti hai # x and y 2 axis # x,y,z 3 axis

In [ ]:
# pehli axis depth , 2 axis row , 3 axis column
dim_3=np.array([[[1,2,3],[4,5,6]]]) # page ka samna row and column pir uskey peechy depth hongai #pehly depth acess hota hai phir row and column hota hai 