In [4]:
import numpy as np

In [5]:
#indexing mei value nikalta hai
#slicing mei dimension ata hai
#axis zero rows hoti hai
#axis one columns hoti hai
#row ko add karney kai lie axis 1 dena parey ga # important for exams
#column ko add karney kai lie axis 0 dena parey ga # important for exams

In [7]:
data1=np.array([[1,2,3],[2,3,4],[5,6,7]])
print(data1)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [9]:
print(data1[:2,1:])

[[2 3]
 [3 4]]


In [21]:
print(data1[2:,:])
print(data1[2]) # it is a vector of 1 dimension
print(data1[2:,:])

[[5 6 7]]
[5 6 7]
[[5 6 7]]


In [12]:
print(data1[:,:2])


[[1 2]
 [2 3]
 [5 6]]


In [14]:
print(data1[1,:2])
print(data1[1:2,:2])

[2 3]
[[2 3]]


In [22]:
#transpose ka matlab axis ko rotate karna

In [29]:
data2=np.arange(16).reshape([2,4,2])
print(data2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [32]:
x=data2.transpose()
print(x)

[[[ 0  8]
  [ 2 10]
  [ 4 12]
  [ 6 14]]

 [[ 1  9]
  [ 3 11]
  [ 5 13]
  [ 7 15]]]


In [33]:
#depth shows number of frames or number of pages
#transpose also transform depth
#but swapaxes does not transform depth
#maximum pehly wo dekho dono rows mei jo bara hoga wo us array ka part bn jayega

In [34]:
#absolute value means modulus if x is neagtive then answer would become positive if x in positive and axwer would become positive
#boolean indexing

In [36]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [37]:
print(data)

[[-0.92965802  0.97593328 -0.412788    0.37702631]
 [ 0.97937989  0.89867921  1.31446272  0.34288285]
 [-1.30644105  0.29560187 -0.24934407  0.80072192]
 [ 0.27574664 -1.23439499 -1.11067646 -1.27071473]
 [-0.18091848  1.31962561  0.08128325  1.47941524]
 [ 1.0528807   0.5327873  -0.18255761  0.80585443]
 [-0.47446786 -0.39306069 -0.11584185 -0.77461494]]


name=='Bob'

In [39]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [42]:
names[data]

IndexError: arrays used as indices must be of integer (or boolean) type

In [44]:
data[names=='Bob']

array([[-0.92965802,  0.97593328, -0.412788  ,  0.37702631],
       [ 0.27574664, -1.23439499, -1.11067646, -1.27071473]])

In [45]:
#sirf wohi rows pick ki hai jis mei name true hai jese array create ki jis mei pehly bob hai or 4 bob to wo true hogaya phir whi rows pick jis mei app ko data true chie tha

In [48]:
cond=names=='Bob'
data[~cond]#it is not using negative sign instead using ~
#it is always picking false instead of true just like as previous

array([[ 0.97937989,  0.89867921,  1.31446272,  0.34288285],
       [-1.30644105,  0.29560187, -0.24934407,  0.80072192],
       [-0.18091848,  1.31962561,  0.08128325,  1.47941524],
       [ 1.0528807 ,  0.5327873 , -0.18255761,  0.80585443],
       [-0.47446786, -0.39306069, -0.11584185, -0.77461494]])

In [49]:
#mask is used for data analysis
mask=(names=='Bob')|(names=='Will')

In [50]:
data[mask]

array([[-0.92965802,  0.97593328, -0.412788  ,  0.37702631],
       [-1.30644105,  0.29560187, -0.24934407,  0.80072192],
       [ 0.27574664, -1.23439499, -1.11067646, -1.27071473],
       [-0.18091848,  1.31962561,  0.08128325,  1.47941524]])

In [51]:
#mask is used for data analysis
mask=(names=='Bob')&(names=='Will')

In [52]:
data[mask]

array([], shape=(0, 4), dtype=float64)

In [54]:
data[data<0]=0
print(data)

[[0.         0.97593328 0.         0.37702631]
 [0.97937989 0.89867921 1.31446272 0.34288285]
 [0.         0.29560187 0.         0.80072192]
 [0.27574664 0.         0.         0.        ]
 [0.         1.31962561 0.08128325 1.47941524]
 [1.0528807  0.5327873  0.         0.80585443]
 [0.         0.         0.         0.        ]]


In [57]:
x=np.random.randn(2,2)

In [56]:
print(x)

[[ 0.0242239  -0.44115072]]


In [65]:
#pandas kai data string frame 
#fancy indexing
arr=np.random.randn(8,4)

In [66]:
for i in range(8):
    arr[i]=i

In [67]:
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [68]:
np.ones((5,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [69]:
np.full()

TypeError: full() missing 2 required positional arguments: 'shape' and 'fill_value'

In [70]:
arr[[0,3,5]]# particular rows istarha sai select karsaktey hai

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [72]:
arr[[-3,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [75]:
print(arr)
arr[[1,5,7,2],[0,3,1,2]]  # column ki fancy indexing

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


array([1., 5., 7., 2.])

In [77]:
newx=np.array([[1,2,3],[2,4,6],[7,8,9]])
print(newx)

[[1 2 3]
 [2 4 6]
 [7 8 9]]


In [78]:
newx[[0,1,2],[2,1,0]]

array([3, 4, 7])

In [80]:
arr_rand=np.arange(32).reshape((8,4))
arr_rand

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [81]:
arr_rand[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [82]:
arr_uniq=np.array([1,5,6,8,9,5,8,9])
arr_uniq

array([1, 5, 6, 8, 9, 5, 8, 9])

In [84]:
np.unique(arr_uniq)#set of collection of unique elements # unique discard repeated elements

array([1, 5, 6, 8, 9])

In [85]:
#horizontal stack
#vertical stack

In [86]:
arr=np.arange(15).reshape((5,3))

In [87]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [98]:
x=arr.ravel()# multidimensional array ko single kardeta hai # copy nahi bnata # lekin flaten copy bnadeta hai
x[0]=14
print(x)
print(arr)

[14  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[14  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [100]:
arr=np.arange(15).reshape((5,3))
y=arr.flatten()#flatten mei copy bnjati hai
y[0]=14
print(y)
print(arr)

[14  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [101]:
arr1=np.arange(15).reshape((5,3))
arr2=np.arange(15).reshape((5,3))
np.concatenate((arr1,arr2),axis=0)#axis 0 by rows change

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [102]:
arr1=np.arange(15).reshape((5,3))
arr2=np.arange(15).reshape((5,3))
np.concatenate((arr1,arr2),axis=1) #axis1 by column br change

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11],
       [12, 13, 14, 12, 13, 14]])

In [105]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])